// Generates CATALOG.json: the machine-readable index of every section, block and snippet.
// Agents read this first to find what already exists. `--check` fails if the file is stale.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  ROOT, read, exists, list, nameOf, originOf, parseSchema, parseDoc, parseSectionComment, loadJSON, translate,
} from './lib.mjs';

const locale = loadJSON('locales/en.default.schema.json');
const t = (v) => translate(v, locale) ?? v;

function settingsOf(schema) {
  return (schema?.settings ?? [])
    .filter((s) => s.id)
    .map((s) => {
      const out = { id: s.id, type: s.type, label: t(s.label) };
      if (s.info) out.info = t(s.info);
      if (s.options) out.options = s.options.map((o) => o.value);
      if (s.default !== undefined) out.default = s.default;
      if (s.min !== undefined) Object.assign(out, { min: s.min, max: s.max, step: s.step, unit: s.unit });
      if (s.visible_if) out.visible_if = s.visible_if;
      return out;
    });
}

const code = (src) => src.replace(/{%-?\s*(doc|comment|schema)\s*-?%}[\s\S]*?{%-?\s*end\1\s*-?%}/g, '');

function assetsUsed(src) {
  return [...new Set([...src.matchAll(/'([\w.-]+\.(?:js|css))'\s*\|\s*asset_url/g)].map((m) => `assets/${m[1]}`))];
}

function customElements(src) {
  return [...new Set([...src.matchAll(/<(aw-[a-z0-9-]+)/g)].map((m) => m[1]))];
}

function rendersSnippets(src) {
  return [...new Set([...src.matchAll(/{%-?\s*render\s+'([\w-]+)'/g)].map((m) => m[1]))];
}

const entries = [];
const problems = [];

for (const rel of list('sections', '.liquid')) {
  const src = read(rel);
  const schema = parseSchema(src);
  const doc = parseSectionComment(src);
  if (!doc) problems.push(`${rel}: missing leading {% comment %} with @description`);
  entries.push({
    id: nameOf(rel),
    kind: 'section',
    origin: originOf(rel),
    file: rel,
    name: t(schema?.name),
    description: doc?.description ?? '',
    use_when: doc?.useWhen ?? '',
    accepts_blocks: (schema?.blocks ?? []).map((b) => b.type),
    enabled_on: schema?.enabled_on ?? null,
    presets: (schema?.presets ?? []).map((p) => t(p.name)),
    settings: settingsOf(schema),
    renders: rendersSnippets(code(src)),
    assets: assetsUsed(code(src)),
    elements: customElements(code(src)),
  });
}

for (const rel of list('blocks', '.liquid')) {
  const src = read(rel);
  const schema = parseSchema(src);
  const doc = parseDoc(src);
  if (!doc?.description) problems.push(`${rel}: missing {% doc %} with @description`);
  const id = nameOf(rel);
  entries.push({
    id,
    kind: 'block',
    origin: originOf(rel),
    file: rel,
    name: t(schema?.name),
    description: doc?.description ?? '',
    use_when: doc?.useWhen ?? '',
    private: id.startsWith('_'),
    accepts_blocks: (schema?.blocks ?? []).map((b) => b.type),
    presets: (schema?.presets ?? []).map((p) => t(p.name)),
    settings: settingsOf(schema),
    renders: rendersSnippets(code(src)),
    assets: assetsUsed(code(src)),
    elements: customElements(code(src)),
  });
}

for (const rel of list('snippets', '.liquid')) {
  const src = read(rel);
  const doc = parseDoc(src);
  if (!doc?.description) problems.push(`${rel}: missing {% doc %} with @description`);
  entries.push({
    id: nameOf(rel),
    kind: 'snippet',
    origin: originOf(rel),
    file: rel,
    description: doc?.description ?? '',
    use_when: doc?.useWhen ?? '',
    params: doc?.params ?? [],
    example: doc?.example ?? '',
    renders: rendersSnippets(code(src)),
  });
}

// Global Theme settings: what an agent may change in config/settings_data.json (use `npm run settings`).
const themeSettings = loadJSON('config/settings_schema.json')
  .filter((g) => g.settings)
  .map((g) => ({ group: t(g.name), settings: settingsOf(g) }));
const schemeGroup = themeSettings.flatMap((g) => g.settings).find((s) => s.type === 'color_scheme_group');
const rawSchemeGroup = loadJSON('config/settings_schema.json').flatMap((g) => g.settings ?? []).find((s) => s.type === 'color_scheme_group');
if (schemeGroup && rawSchemeGroup) {
  schemeGroup.roles = rawSchemeGroup.definition.map((d) => ({ id: d.id, type: d.type, label: t(d.label), default: d.default }));
}

const catalog = {
  $comment: 'GENERATED by scripts/build-catalog.mjs from Liquid schemas and docs. Do not edit; run `npm run build:catalog`.',
  theme: loadJSON('package.json').version,
  counts: {
    sections: entries.filter((e) => e.kind === 'section').length,
    blocks: entries.filter((e) => e.kind === 'block').length,
    snippets: entries.filter((e) => e.kind === 'snippet').length,
  },
  theme_settings: themeSettings,
  entries,
};

const out = `${JSON.stringify(catalog, null, 2)}\n`;
if (problems.length) {
  console.error(problems.map((p) => `  - ${p}`).join('\n'));
}
if (process.argv.includes('--check')) {
  if (!exists('CATALOG.json') || read('CATALOG.json') !== out) {
    console.error('CATALOG.json is out of date. Run: npm run build:catalog');
    process.exit(1);
  }
  console.log('CATALOG.json is up to date.');
} else {
  writeFileSync(join(ROOT, 'CATALOG.json'), out);
  console.log(`Wrote CATALOG.json (${entries.length} entries).`);
}
if (problems.length) process.exit(1);
