// Generates CLASS_VOCAB.md from src/vocab.css. `--check` fails if the file is stale.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, read, exists, expandBraces } from './lib.mjs';

const src = read('src/vocab.css');
const groups = [];
let current = null;
for (const line of src.split('\n')) {
  const g = line.match(/\/\*\s*group:\s*(.+?)\s*\*\//);
  if (g) {
    current = { name: g[1], classes: [] };
    groups.push(current);
    continue;
  }
  const s = line.match(/@source\s+inline\("([^"]+)"\)/);
  if (s && current) {
    for (const token of s[1].split(/\s+/).filter(Boolean)) current.classes.push(...expandBraces(token));
  }
}

const total = groups.reduce((n, g) => n + g.classes.length, 0);
let md = `<!-- GENERATED by scripts/build-vocab.mjs from src/vocab.css. Do not edit. -->
# Class vocabulary

These ${total} classes are **always** present in \`assets/app.css\`.

Use them when you edit Liquid **without running the build** (Shopify admin code editor, Sidekick, the "Custom Liquid" block).
If you work in this repo with \`npm run dev\` or \`npm run build\`, any Tailwind class works — the build adds it.

Colors are theme tokens (\`bg-primary\`, \`text-fg\`…), never raw palette colors like \`red-500\`.
Responsive prefixes: \`md:\` = 750px and up, \`lg:\` = 990px and up (only where listed).

`;
for (const g of groups) {
  md += `## ${g.name}\n\n\`${g.classes.join('` `')}\`\n\n`;
}

const target = 'CLASS_VOCAB.md';
if (process.argv.includes('--check')) {
  if (!exists(target) || read(target) !== md) {
    console.error(`${target} is out of date. Run: npm run build:vocab`);
    process.exit(1);
  }
  console.log(`${target} is up to date (${total} classes).`);
} else {
  writeFileSync(join(ROOT, target), md);
  console.log(`Wrote ${target} (${total} classes).`);
}
